spring:
  application.name: minikube-demo
  main:
    banner-mode: off
    lazy-initialization: false
  lifecycle:
    timeout-per-shutdown-phase: 20s

logging:
  level:
    root: INFO
    org.springframework: INFO

server:
  port: 8080
  servlet:
    context-path: /
  # See also https://docs.spring.io/spring-boot/docs/2.7.9/reference/html/application-properties.html#appendix.application-properties.server
  tomcat:
    accept-count: 10
    max-connections: 400
    threads:
      max: 10
      min-spare: 5 # actuator port uses the same configuration
  shutdown: graceful

management:
  server:
    port: 8090
  endpoints:
    enabled-by-default: false
    web.exposure.include: health,prometheus,info,threaddump,heapdump
  endpoint:
    health:
      enabled: true
      probes.enabled: true
      group:
        readiness:
          include: readinessState,managable
          additional-path: server:/readyz # In order to collect probes from application main port
          show-components: always
    prometheus:
      enabled: true
    info:
      enabled: true
    threaddump:
      enabled: true
    heapdump:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      minimum-expected-value:
        http.server.requests: 10ms
      maximum-expected-value:
        http.server.requests: 10s
      slo:
        http.server.requests: 1s
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
